[pytest]

markers =
    login: 这是登录测试用例

addopts = -s -v

# 修改用例路径读取规则
testpaths = ./pytest_demo

# 修改用例文件读取规则
python_files = test_*.py

# 修改用例类的读取规则
python_classes = Test*

# 修改用例函数的读取规则
python_functions = test_*


